server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql